### PR TITLE
Reduced code duplication as much as possible

### PR DESCRIPTION
**Pull request by BasKiers**
Also fixed some small errors like duplicate var declaration and not declared variable references.

I've tried to reduce code duplication without impacting the ability to customize each animation. Animations are now stored in a large array containing arrays for each animation type. Each animation type array has entries for multiple colors and the `.map` at the and of the array sets some default parameters like the frame generator function and the screensaver fps options. This large array of animation type arrays is squashed and looped over to register the arrays in Homey. 

I hope you find this solution better maintainable and make it easier for you add/remove screensavers and customize individual screensavers while keeping a good overview of your changes.

### CODE REVIEW

**Comment by OpenMindNL** [comment]
Hello Bas. I appreciate your corrections and changes. I did not test your code yet, but I might have spotted a mistake at line 92.
id: animation_led_triangle_rgb_fast should be id: led_triangle_rgb_fast I think.

I'm completely new to working with GitHub. Maybe you could give me a little help? Do I need to change the code myself and re-upload the files to GitHub, or is it possible to accept your changes somewhere and create the new files automatically?
Thanks, Alex.

ps: About the slow opening LED Ring page in the desktop app: I think this is a bug in the app, because the screensaver list loads very quick at Flow: ...dan ... Zet Screensaver.

**Review by OpenMindNL — CHANGES_REQUESTED** [review]
Great code optimizing! However, I found 3 mistakes. The 'animation_' prefix should be removed from 'led_triangle_rgb_fast'. And there are two wrong color codes. 'led_scanner_red' should be 255,0,0 instead of 255,127,0. And 'led_lighthouse_yellow' should be 255,255,0 instead of 255,0,255. Thank you!

**Comment by BasKiers** [comment]
Hi,

I fixed the typo's you pointed out. I also changed the `animation_led_triangle_rgb_fast` id although it was named like that in the original code. Could you test if the name change works? If you accept the changes you can press the "merge pull request" button which will add my changes to your repository. After that you can pull these changes to your own computer by typing `git pull` in your terminal.

**Comment by OpenMindNL** [comment]
I already checked the code yesterday. That's how I discovered the wrong color codes ;-)
I just merged the changes, and copy-pasted the new raw-code to the app.js on my PC. I uploaded the code to my Homey and checked each screensaver again. Everything is fine now. 8-) BTW: In the original code, the animation_ prefix was used for the variable names. The screensaver-ids didn't have the prefix. Nevertheless, thank you very much!

**Pull request merged**
