### PR TITLE
NEW: refactor to SDK 2

### PR DESCRIPTION
**Pull request by martijnpoppen**
Did a refactor to SDK v2. So with this it will work with Homey v5

### CODE REVIEW

**Comment by OpenMindNL** [comment]
OK. I assume this will work. But get me started as it has been 3 years since I last did anything with Homey apps. I now have to choose "Merge Pull request" ... what then? How did updating to Athom go again?

**Comment by martijnpoppen** [comment]
Updating a Homey app is via the terminal.
You have to install Homey globally via npm. `npm install -g homey`
Then run `homey app publish`

**Comment by OpenMindNL** [comment]
Sorry ... but this doesn't mean anything to me. I also no longer have any development software on my PC. A few years ago I think there was a simple method of reporting to Athom via Github. I don't want to install on my Homey, but I want to pass the update on to Athom after merging the pull request. I wont check if it works.

**Comment by martijnpoppen** [comment]
You can also pass the app to me if you want and i'll do the update and maybe future support. You can do that via https://developer.athom.com/apps.
Select you app. Click transfer app. And use this id: `5e2daad2e3e0da0ca754b6a8`

**Comment by OpenMindNL** [comment]
thanks. I think that passing the app to you might be a good idea but I don't see a transfer option at https://developer.athom.com/apps/app/openmindnl.ledcollection

**Comment by martijnpoppen** [comment]
It's a red button at the bottom of the page

**Comment by OpenMindNL** [comment]
Wait.. it's at the end of the page...

**Comment by OpenMindNL** [comment]
:-D

**Comment by OpenMindNL** [comment]
App successfully transfered

**Comment by martijnpoppen** [comment]
Thanks! Will update to the new SDK :) 
Also will do it from my github, so you can ignore this PR

**Comment by OpenMindNL** [comment]
I guess you'll make a lot of users happy. Succes!

**Comment by OpenMindNL** [comment]
I did not do any pull request before transfer, so you'll still have to do your updates. :-)

**Comment by martijnpoppen** [comment]
Yes! will do 👍

**Pull request closed without merging**
